import math
from functools import lru_cache
from typing import Sequence

import numpy as np
import torch
import torch.nn.functional as F

from cellfinder.core.tools.array_operations import bin_mean_3d
from cellfinder.core.tools.geometry import make_sphere


class InvalidVolume(ValueError):
    """
    Raised when the volume passed to BallFilter is too small or does not meet
    requirements.
    """

    pass


@lru_cache(maxsize=50)
def get_kernel(ball_xy_size: int, ball_z_size: int) -> np.ndarray:
    """
    Create a spherical kernel.

    This is done by:
    1. Generating a binary sphere at a resolution *upscale_factor* larger
       than desired.
    2. Downscaling the binary sphere to get a 'fuzzy' sphere at the
       original intended scale
    """
    upscale_factor: int = 7
    upscaled_kernel_shape = (
        upscale_factor * ball_xy_size,
        upscale_factor * ball_xy_size,
        upscale_factor * ball_z_size,
    )
    # subtract one b/c we need to shift from size/count to index
    upscaled_ball_centre_position = [
        (u - 1) / 2 for u in upscaled_kernel_shape
    ]
    upscaled_ball_radius = [u / 2 for u in upscaled_kernel_shape]

    sphere_kernel = make_sphere(
        upscaled_kernel_shape,
        upscaled_ball_radius,
        upscaled_ball_centre_position,
    )
    sphere_kernel = sphere_kernel.astype(np.float32)
    kernel = bin_mean_3d(
        sphere_kernel,
        bin_width=upscale_factor,
        bin_height=upscale_factor,
        bin_depth=upscale_factor,
    )

    assert (
        kernel.shape[2] == ball_z_size
    ), "Kernel z dimension should be {}, got {}".format(
        ball_z_size, kernel.shape[2]
    )

    return kernel


class BallFilter:
    """
    A 3D ball filter.

    This runs a spherical kernel across the 2d planar dimensions
    of a *ball_z_size* stack of planes, and marks pixels in the middle
    plane of the stack that have a high enough intensity over the
    spherical kernel.

    Parameters
    ----------
    plane_height, plane_width : int
        Height/width of the planes.
    ball_xy_size : int
        Diameter of the spherical kernel (in voxels) in the x/y dimensions.
    ball_z_size : int
        Diameter of the spherical kernel in the z dimension in voxels.
        Determines the number of planes stacked to filter
        the central plane of the stack.
    overlap_fraction : float
        The fraction of pixels within the spherical kernel that
        have to be over *threshold_value* for a pixel to be marked
        as having a high intensity.
    threshold_value : int
        Value above which an individual pixel is considered to have
        a high intensity.
    soma_centre_value : int
        Value used to mark pixels with a high enough intensity.
    tile_height, tile_width : int
        Width/height of individual tiles in the mask generated by
        2D filtering.
    dtype : str
        The data-type of the input planes and the type to use internally.
        E.g. "float32".
    batch_size: int
        The number of planes that will be typically passed in a single batch to
        `append`. This is only used to calculate `num_batches_before_ready`.
        Defaults to 1.
    torch_device: str
        The device on which the data and processing occurs on. Can be e.g.
        "cpu", "cuda" etc. Defaults to "cpu". Any data passed to the filter
        must be on this device. Returned data will also be on this device.
    use_mask : bool
        Whether tiling masks will be used in `append`. If False, tile masks
        won't be passed in and/or will be ignored. Defaults to True.
    """

    num_batches_before_ready: int
    """
    The number of batches of size `batch_size` passed to `append`
    before `ready` would return True.
    """

    # the inside brain tiled mask, if tiles are used (use_mask is True)
    inside_brain_tiles: list[torch.Tensor] = []

    def __init__(
        self,
        plane_height: int,
        plane_width: int,
        ball_xy_size: int,
        ball_z_size: int,
        overlap_fraction: float,
        threshold_value: int,
        soma_centre_value: int,
        tile_height: int,
        tile_width: int,
        dtype: str,
        batch_size: int = 1,
        torch_device: str = "cpu",
        use_mask: bool = True,
    ):
        self.ball_xy_size = ball_xy_size
        self.ball_z_size = ball_z_size
        self.overlap_fraction = overlap_fraction
        self.tile_step_height = tile_height
        self.tile_step_width = tile_width
        self.use_mask = use_mask

        d1 = plane_height
        d2 = plane_width
        ball_xy_size = self.ball_xy_size
        if d1 < ball_xy_size or d2 < ball_xy_size:
            raise InvalidVolume(
                f"Invalid plane size {d1}x{d2}. Needs to be at least "
                f"{ball_xy_size} in each dimension"
            )

        self.THRESHOLD_VALUE = threshold_value
        self.SOMA_CENTRE_VALUE = soma_centre_value

        # kernel comes in as XYZ, change to ZYX so it aligns with data
        kernel = np.moveaxis(get_kernel(ball_xy_size, self.ball_z_size), 2, 0)
        self.overlap_threshold = np.sum(self.overlap_fraction * kernel)
        self.kernel_xy_size = kernel.shape[-2:]
        self.kernel_z_size = self.ball_z_size

        # convert to right type and pin for faster copying
        kernel = torch.from_numpy(kernel).type(getattr(torch, dtype))
        if torch_device != "cpu":
            # torch at one point threw a cuda memory error when splitting cells
            # on cpu due to pinning. It's best to only pin on using cuda
            kernel.pin_memory()
        self.kernel = kernel.to(device=torch_device, non_blocking=True)

        self.num_batches_before_ready = int(
            math.ceil(self.ball_z_size / batch_size)
        )
        # Stores the current planes that are being filtered. Elements are z
        self.planes = []
        # Index of the middle plane in the volume
        self.middle_z_idx = int(np.floor(self.ball_z_size / 2))
        # the raw input planes, we track along with the filtered planes
        self.raw_planes: list[np.ndarray] = []

        if not use_mask:
            return
        self.n_vertical_tiles = int(
            np.ceil(plane_height / self.tile_step_height)
        )
        self.n_horizontal_tiles = int(
            np.ceil(plane_width / self.tile_step_width)
        )
        # Stores tile masks. Elements are z
        self.inside_brain_tiles = []

    @classmethod
    def min_xy_padding(cls, ball_xy_size: int) -> tuple[int, int]:
        """
        For a given ball x/y kernel size, it returns the padding needed for the
        plane so the full input data is filtered. Otherwise, data on the
        edges of the plane will be zeros because the center of the ball will
        never be over it. Adding padding will ensure the ball center will be
        over all input data.

        Parameters
        ----------
        ball_xy_size: int
            The x/y kernel (ball) size in voxels.

        return
        ----------
        padding: 2-tuple of ints
            The padding to add to the start and end of the data to have all
            input data considered.
        """
        n = ball_xy_size
        # e.g. if starting with just 1 voxel: if kernel is even, say 4, then
        # left padding will be 1 and right 2. This gives a single voxel output.
        # If odd, say 5, it'll be 2 on each side
        left = (n - 1) // 2
        right = n - 1 - left
        return left, right

    @classmethod
    def min_z_padding(cls, ball_z_size: int) -> tuple[int, int]:
        """
        Same as for `min_xy_padding`, except in the z-dimension.
        """
        n = ball_z_size
        # e.g. if starting with just 1 voxel: if kernel is even, say 4, then
        # left padding will be 1 and right 2. This gives a single voxel output.
        # If odd, say 5, it'll be 2 on each side
        bottom = (n - 1) // 2
        top = n - 1 - bottom
        return bottom, top

    @property
    def ready(self) -> bool:
        """
        Return whether enough planes have been appended to run the filter
        using `walk`.
        """
        return len(self.planes) >= self.kernel_z_size

    def append(
        self,
        planes: torch.Tensor | Sequence[torch.Tensor],
        masks: torch.Tensor | Sequence[torch.Tensor] | None = None,
        raw_planes: np.ndarray | Sequence[np.ndarray] | None = None,
    ) -> None:
        """
        Add a new z-stack to the filter.

        Previous stacks passed to `append` are removed, except enough planes
        at the top of the previous z-stack to provide padding so we can filter
        starting from the first plane in `planes` (or continue filtering planes
        at the end of the last stack). The first time we call `append`,
        `first_valid_plane` is the first plane to actually be filtered in the
        z-stack due to lack of padding before the zeroth plane.

        So make sure to call `walk` and
        `get_processed_planes`/`get_raw_planes` to get the results before
        calling `append` again.

        Parameters
        ----------
        planes : torch.Tensor
            The 2d filtered z-stack. There can be one or more planes in the
            stack, but it must have 3 dimensions. Input data is not modified.
        masks : torch.Tensor
            A z-stack tile mask, indicating for each tile whether it's in or
            outside the brain. If the latter it's excluded.

            If `use_mask` was True, this must be provided. If False, this
            parameter will be ignored.

            Input data is not modified.
        raw_planes : np.ndarray or None
            The original input data z-stack. There can be one or more planes in
            the stack, but it must have 3 dimensions. Input data is not
            modified.

            If provided, the planes can be gotten via `get_raw_planes`.
        """
        if len(self.planes):
            if len(self.planes) < self.kernel_z_size:
                num_remaining_with_padding = len(self.planes)
            else:
                num_remaining = self.kernel_z_size - (self.middle_z_idx + 1)
                num_remaining_with_padding = num_remaining + self.middle_z_idx
            remaining_start = len(self.planes) - num_remaining_with_padding

            del self.planes[:remaining_start]
            self.planes.extend(planes)

            if raw_planes is not None:
                del self.raw_planes[:remaining_start]
                self.raw_planes.extend(raw_planes)

            if self.use_mask:
                del self.inside_brain_tiles[:remaining_start]
                self.inside_brain_tiles.extend(masks)
        elif self.middle_z_idx > 0:
            # need to pad the start before middle plane
            pad = self.middle_z_idx

            pad_planes = torch.zeros(
                (pad, *planes[0].shape),
                dtype=planes[0].dtype,
                device=planes[0].device,
            )
            self.planes = list(pad_planes) + list(planes)

            if self.use_mask:
                pad_inside = torch.zeros(
                    (pad, *masks[0].shape),
                    dtype=masks[0].dtype,
                    device=masks[0].device,
                )
                self.inside_brain_tiles = list(pad_inside) + list(masks)

            if raw_planes is not None:
                # if ndarray it's converted to list of planes, otherwise it's
                # already a list of planes that is copied
                self.raw_planes = list(raw_planes)
        else:
            self.planes = list(planes)

            if self.use_mask:
                self.inside_brain_tiles = list(masks)

            if raw_planes is not None:
                # if ndarray it's converted to list of planes, otherwise it's
                # already a list of planes that is copied
                self.raw_planes = list(raw_planes)

    def flush(self) -> bool:
        """
        Ensure to get unprocessed planes, because this calls append.
        """
        # we need this many at end to process last plane
        pad = self.ball_z_size - self.middle_z_idx - 1

        if not self.planes or not pad:
            return False

        plane = self.planes[0]

        pad_planes = torch.zeros(
            (pad, *plane.shape),
            dtype=plane.dtype,
            device=plane.device,
        )
        pad_inside = None
        if self.use_mask:
            inside = self.inside_brain_tiles[0]
            pad_inside = torch.zeros(
                (pad, *inside.shape),
                dtype=inside.dtype,
                device=inside.device,
            )

        self.append(pad_planes, pad_inside)

        return True

    def get_processed_planes(self) -> list[np.ndarray]:
        """
        After passing enough planes to `append`, and after `walk`, this returns
        a copy of the processed planes as a single numpy z-stack.

        It only starts returning planes corresponding to plane
        `first_valid_plane` relative to the first planes passed to `append`.
        E.g. if `ball_z_size` is 3 and `first_valid_plane` is 1, and you passed
        5 planes total to `append`, then this will have returned planes [1, 3].

        Notice the last plane was not included, because we return only "middle"
        planes - planes that can correspond to the center of a ball.
        """
        if not self.ready:
            raise TypeError("Not enough planes were appended")

        num_processed = len(self.planes) - self.kernel_z_size + 1
        assert num_processed
        middle = self.middle_z_idx
        planes = [
            p.cpu().numpy().copy()
            for p in self.planes[middle : middle + num_processed]
        ]

        return planes

    def get_raw_planes(self) -> list[np.ndarray]:
        """
        Same as `get_processed_planes`, except that it returns the raw input
        planes, corresponding to the planes in the z-stack of
        `get_processed_planes` for the same batch.

        The planes are returned as a list of 2d numpy arrays, one per plane.

        This will only return valid results if the raw planes were provided
        in *all* calls to `append`.
        """
        if not self.ready:
            raise TypeError("Not enough planes were appended")

        num_processed = len(self.planes) - self.kernel_z_size + 1
        assert num_processed

        raw_planes = self.raw_planes[:num_processed]
        return raw_planes

    def walk(self) -> None:
        """
        Applies the filter to all the planes passed to `append`.

        May only be called if `ready` was True.

        You can get the processed planes from `get_processed_planes`.
        """
        if not self.ready:
            raise TypeError("Called walk before enough planes were appended")

        _walk(
            self.kernel_z_size,
            self.middle_z_idx,
            self.tile_step_height,
            self.tile_step_width,
            self.overlap_threshold,
            self.THRESHOLD_VALUE,
            self.SOMA_CENTRE_VALUE,
            self.kernel,
            self.planes,
            self.inside_brain_tiles if self.use_mask else None,
        )


@torch.jit.script
def _walk(
    kernel_z_size: int,
    middle: int,
    tile_step_height: int,
    tile_step_width: int,
    overlap_threshold: float,
    threshold_value: int,
    soma_centre_value: int,
    kernel: torch.Tensor,
    planes: list[torch.Tensor],
    inside_brain_tiles: list[torch.Tensor] | None,
):
    num_process = len(planes) - kernel_z_size + 1
    height, width = planes[0].shape
    kz, kh, kw = kernel.shape
    plane_h = height - kh + 1
    plane_w = width - kw + 1

    # threshold volume so it's zero/one. And add two dims at start so
    # it's 11YX
    planes_tresh = [(p >= threshold_value).type(kernel.dtype) for p in planes]

    # we do a plane at a time, planes: i:i+kz, for plane i+middle
    for i in range(num_process):
        # spherical kernel is symmetric so convolution=correlation. Use
        # binary threshold mask over the kernel to sum the value of the
        # kernel at voxels that are bright
        overlap = torch.zeros(
            (plane_h, plane_w), dtype=kernel.dtype, device=kernel.device
        )
        for plane, k_plane in zip(planes_tresh[i : i + kz], kernel):
            overlap_plane = F.conv2d(
                plane[None, None, ...],
                k_plane[None, None, ...],
                padding="valid",
            )
            overlap += overlap_plane[0, 0, :, :]
        # overlap = F.conv3d(
        #     torch.stack(planes_tresh[i : i + kz])[None, None, ...],
        #     kernel[None, None, ...],
        #     padding="valid"
        # )[0, 0, 0, :, :]
        overlaps = overlap > overlap_threshold

        # only edit the volume that is valid - conv excludes edges so we
        # only edit the plane parts returned by conv3d
        height_valid, width_valid = overlaps.shape
        height_offset = (height - height_valid) // 2
        width_offset = (width - width_valid) // 2
        sub_plane = planes[i + middle][
            height_offset : height_offset + height_valid,
            width_offset : width_offset + width_valid,
        ]

        # do we use tile masks or just overlapping?
        if inside_brain_tiles is not None:
            # unfold tiles to cover the full voxel area each tile covers
            inside = (
                inside_brain_tiles[i + middle][:, :]
                .repeat_interleave(tile_step_height, dim=0)
                .repeat_interleave(tile_step_width, dim=1)
            )
            # again only process pixels in the valid area
            inside = inside[
                height_offset : height_offset + height_valid,
                width_offset : width_offset + width_valid,
            ]

            # must have enough ball overlap to be bright/tile is in brain
            sub_plane[torch.logical_and(overlaps, inside)] = soma_centre_value

        else:
            # must have enough ball overlap to be bright
            sub_plane[overlaps] = soma_centre_value
